import { SideBar } from "@/components/SideBar";
import type { Metadata } from "next";
import "./globals.css";
import { Lato } from "next/font/google";
import { Navbar } from "@/components/nav";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        <div className="flex h-screen">
          <SideBar />
          <main className="flex-1 overflow-y-auto">
            <Navbar />
            <div className="bg-slate-50">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
